/**
 * Dumpea data de local.db a un .sql con INSERTs idempotentes para D1.
 * Orden importante: stickers/extras/users primero, luego colecciones (FK).
 */
import Database from 'better-sqlite3';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { writeFileSync } from 'node:fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DB_PATH = resolve(__dirname, '..', process.env.DATABASE_URL ?? 'local.db');
const OUT = resolve(__dirname, '..', 'drizzle', 'data.sql');

const db = new Database(DB_PATH, { readonly: true });

// Columnas válidas en el schema target (drizzle/0000_gray_mojo.sql).
// Si local.db tiene columnas extra (ej. extras.tengo/repetidas del modelo viejo
// single-user) las descartamos — el dump no debería incluirlas.
const TARGET: Record<string, string[]> = {
	stickers: ['id', 'equipo', 'confederacion', 'numero', 'tipo', 'descripcion'],
	extras: ['id', 'jugador', 'variante'],
	users: ['id', 'token', 'nombre', 'email', 'password_hash', 'is_admin', 'created_at', 'claimed_at'],
	colecciones: ['user_id', 'sticker_id', 'tengo', 'repetidas'],
	imports: ['id', 'fecha', 'submitter_id', 'to_user_id', 'status', 'origen'],
	login_attempts: ['id', 'ip', 'fecha', 'success']
};
const ORDER = Object.keys(TARGET);

function quote(v: unknown): string {
	if (v === null || v === undefined) return 'NULL';
	if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
	if (typeof v === 'bigint') return v.toString();
	if (typeof v === 'boolean') return v ? '1' : '0';
	if (Buffer.isBuffer(v)) return `X'${v.toString('hex')}'`;
	return `'${String(v).replace(/'/g, "''")}'`;
}

const out: string[] = ['-- generated by scripts/dump-to-sql.ts'];

for (const table of ORDER) {
	const cols = TARGET[table];
	const selectSql = cols.map((c) => `"${c}"`).join(', ');
	const rows = db.prepare(`SELECT ${selectSql} FROM ${table}`).all() as Record<string, unknown>[];
	if (!rows.length) {
		out.push(`-- ${table}: 0 rows`);
		continue;
	}
	const colsSql = cols.map((c) => `"${c}"`).join(', ');
	out.push(`-- ${table}: ${rows.length} rows`);
	for (const row of rows) {
		const values = cols.map((c) => quote(row[c])).join(', ');
		out.push(`INSERT OR REPLACE INTO "${table}" (${colsSql}) VALUES (${values});`);
	}
}

writeFileSync(OUT, out.join('\n'), 'utf8');
console.log(`wrote ${OUT}`);
